global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]  # Prometheus scraping itself for metrics

  - job_name: "diagnostic-sender"
    static_configs:
      - targets: ['host.docker.internal:9100']  # Scraping your custom exporter
    scrape_interval: 15s

