scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prom-config.onrender.com:9090"]  # Remove https://
  - job_name: "diagnostic-sender"
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 15s
