scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prom-config.onrender.com"]  
  - job_name: "diagnostic-sender"
    static_configs:
      - targets: [' 172.23.112.1:8080']
    scrape_interval: 15s
