scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]  # Nome del servizio di Prometheus
  - job_name: "diagnostic-sender"
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 15s
