{
 "title": "Medical Machine General Informations Copy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "scanType", "label": "Scan Type", "query": { "query": "label_values(type)" } },
   { "name": "operator_type", "label": "Operator Type", "query": { "query": "label_values(operator_type)" } },
   { "name": "machine_model", "label": "Model", "query": { "query": "label_values(model)" } },
   { "name": "machine_serial", "label": "Serial", "query": { "query": "label_values(serial)" } }
  ]
 },
 "panels": [
  {
   "title": "Machine Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(1, max(ct_scanner_model{model=~\"$machine_model\",serial=~\"$machine_serial\",operator_type=~\"$operator_type\"}) by (model, serial, operator_type,sw_version,first_acquisition,last_acquisition))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "ct_scanner_metrics{type=\"$scanType\",user_type=\"$operator_type\", station_model=\"$machine_model\",station_sn=\"$machine_serial\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Temperature",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_temperature_count{range=\"danger\", machine_model=\"$machine_model\", machine_serial=\"$machine_serial\", operator_type=\"$operator_type\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "system_temperature_count{range=\"normal\",machine_model=\"$machine_model\", machine_serial=\"$machine_serial\", operator_type=\"$operator_type\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "system_temperature_count{range=\"high\", machine_model=\"$machine_model\", machine_serial=\"$machine_serial\", operator_type=\"$operator_type\"}\r\n",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Anode Temperature",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anode_temperature_count{range=\"low\", machine_model=\"$machine_model\", machine_serial=\"$machine_serial\", operator_type=\"$operator_type\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "anode_temperature_count{range=\"normal\", machine_model=\"$machine_model\", machine_serial=\"$machine_serial\", operator_type=\"$operator_type\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "anode_temperature_count{range=\"high\", machine_model=\"$machine_model\", machine_serial=\"$machine_serial\", operator_type=\"$operator_type\"}",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Series Counter ",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "ct_offline_metrics_percentage{status=\"Online\", station_model=\"$machine_model\",station_sn=\"$machine_serial\",operator_type=\"$operator_type\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Acquisition Mode Counter",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ct_shots_metrics{station_model=\"$machine_model\",station_sn=\"$machine_serial\",operator_type=\"$operator_type\",advisor_advanced=\"Advanced\"}",
     "legendFormat": "{{advisor_advanced}}"
    },
    {
     "expr": "ct_shots_metrics{station_model=\"$machine_model\",station_sn=\"$machine_serial\",operator_type=\"$operator_type\",advisor_advanced=\"Advisor\"}\r\n",
     "legendFormat": "{{advisor_advanced}}"
    }
   ]
  },
  {
   "title": "Offline Series Counter",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "ct_offline_metrics_percentage{status=\"Offline\", station_model=\"$machine_model\",station_sn=\"$machine_serial\",operator_type=\"$operator_type\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Temp Percentage (%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_temperature_percentage{range=\"danger\", machine_model=\"$machine_model\", machine_serial=\"$machine_serial\", operator_type=\"$operator_type\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "system_temperature_percentage{range=\"normal\", machine_model=\"$machine_model\", machine_serial=\"$machine_serial\", operator_type=\"$operator_type\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "system_temperature_percentage{range=\"high\", machine_model=\"$machine_model\", machine_serial=\"$machine_serial\", operator_type=\"$operator_type\"}",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Anode Temp Percentage (%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anode_temperature_percentage{range=\"low\",machine_model=\"$machine_model\",machine_serial=\"$machine_serial\",operator_type=\"$operator_type\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "anode_temperature_percentage{range=\"normal\",machine_model=\"$machine_model\",machine_serial=\"$machine_serial\",operator_type=\"$operator_type\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "anode_temperature_percentage{range=\"high\",machine_model=\"$machine_model\",machine_serial=\"$machine_serial\",operator_type=\"$operator_type\"}\r\n",
     "legendFormat": "{{range}}"
    }
   ]
  }
 ]
}