version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount your Prometheus config
    ports:
      - "9090:9090"  # Expose Prometheus on port 9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus  # Ensure Prometheus starts before Grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini  # Mount your Grafana config
      - ./grafana/provisioning:/etc/grafana/provisioning  # Mount your Grafana provisioning folder
    ports:
      - "3000:3000"  # Expose Grafana on port 3000
    
